### ISSUE TITLE
Some kind of mob crashes my game

### ISSUE THREAD

**Issue by Alsososcar** [czbuendel/EL2Test#74] opened 2021-05-16 15:18 UTC
Modpack Version:  1.02a

A mob that is invisible takes my weapon nad right after the game crashes.

**To Reproduce**
I just play and it pops out of nowhere

The game crashes

I have downloaded Optifine, Create, Mekanism and Thermal series, just for quality of life like magnet and farming. But i have played with those mods so much so i dont think that have anything to do with it.

[latest.log](https://github.com/Engineers-Life/EL2/files/6489447/latest.log)

[crash-2021-05-16_17.09.21-server.txt](https://github.com/Engineers-Life/EL2/files/6489449/crash-2021-05-16_17.09.21-server.txt)

**Comment by czbuendel** [comment] 2021-05-16 20:49
We do not provide support for modified packs, especially ones where 3 content heavy mods have been added that provide wide changing effects. You also did not do the one thing that we request for every issue if you have optifine. It is nice that you have played a lot with those mods but they have not been curated and fixed to play nice with **this** pack. 

So if you cannot repeat the issue without all the mod additions then this will be closed.

And looking through the crash log it is a ticking entity caused by a Vex.

**Comment by D0CTOR-ZED** [comment] 2021-05-16 21:14
Closing issue due to the inclusion of other mods.  Optifine in particular can be the source of errors.  While I support that players can add additional mods if that is what they want to do, it also isn't something that we should spend our time troubleshooting.  If you encounter the same issue in an unmodified version of the pack, feel free to reopen the issue.

**Closed as completed by D0CTOR-ZED** 2021-05-16 21:14 UTC
Labels: invalid
